#!/usr/bin/env sh
set -e

# No rebase without commited changes
if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "pre-rebase: working tree is dirty. Commit or stash changes before rebase."
  exit 1
fi

# Remind to turn on linear history on pull
if ! git config --get pull.rebase >/dev/null; then
  echo "pre-rebase: consider 'git config pull.rebase true' for linear history."
fi